### ISSUE TITLE
Custom Save Image node does not visialize or save images produced

### ISSUE THREAD

**Issue by DavideAlidosi** [kk8bit/KayTool#3]
Hello and thank you for your work.
Currently, the Custom Save Image node does not save the generated images or display them.
I am using the latest ComfyUI commit available on windows 10.
Thanks for the support.

**Comment by kk8bit** [comment]
Please attach your screenshots or provide a clearer description of your working environment. Alternatively, include your terminal report. Thank you! I will review the code to verify whether it can correctly locate the folder on Windows.

**Comment by DavideAlidosi** [comment]
```
L:\ComfyUI_FLUX_1.0>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-18 07:07:57.537919
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: L:\ComfyUI_FLUX_1.0\python_embeded\python.exe
** ComfyUI Path: L:\ComfyUI_FLUX_1.0\ComfyUI
** Log path: L:\ComfyUI_FLUX_1.0\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.7 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24575 MB, total RAM 65467 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: L:\ComfyUI_FLUX_1.0\ComfyUI\web
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
### Loading: ComfyUI-Impact-Pack (V7.11.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[WARN] ComfyUI-Impact-Pack: custom_wildcards path not found: L:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\custom_wildcards. Using default path.
[Impact Pack] Wildcards loading done.
Total VRAM 24575 MB, total RAM 65467 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2835 [d9f90965] | Released on '2024-11-17'
L:\ComfyUI_FLUX_1.0
############################################
L:\ComfyUI_FLUX_1.0\custom_nodes\ComfyUI-Universal-Styler\CSV
############################################
[]
############################################
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

[rgthree-comfy] Loaded 42 magnificent nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Believe you can and you're halfway there." - Theodore Roosevelt


Import times for custom nodes:
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension
   0.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Fluxpromptenhancer
   0.1 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\KayTool
   0.3 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.4 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
   0.7 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.0 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\comfyui-dynamicprompts
   1.9 seconds: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
New prompt: Professional photography, 35mm film, sharp lens, full shot photo of a man. Daytime outdoor location. Professional lighting and color grading for a clean sharp film look. Extreme details like in a professional macro photography.
L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py:79: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:212.)
  torch_tensor = torch.from_numpy(tensor.data) # mmap

ggml_sd_loader:
 12                            161
 0                              50
 13                              7
 14                              1

ggml_sd_loader:
 0                             471
 12                            304
 1                               5
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
Number of sigmas: 17, Number of schedule steps: 16
Adjusting sigma at index 0 with multiplier 0.0
Adjusting sigma at index 1 with multiplier 0.0
Adjusting sigma at index 2 with multiplier 0.020000000000000004
Adjusting sigma at index 3 with multiplier 0.020000000000000004
Adjusting sigma at index 4 with multiplier 0.020000000000000004
Adjusting sigma at index 5 with multiplier 0.020000000000000004
Adjusting sigma at index 6 with multiplier 0.020000000000000004
Adjusting sigma at index 7 with multiplier 0.020000000000000004
Adjusting sigma at index 8 with multiplier 0.020000000000000004
Adjusting sigma at index 9 with multiplier 0.020000000000000004
Adjusting sigma at index 10 with multiplier 0.020000000000000004
Adjusting sigma at index 11 with multiplier 0.020000000000000004
Adjusting sigma at index 12 with multiplier 0.020000000000000004
Adjusting sigma at index 13 with multiplier 0.020000000000000004
Adjusting sigma at index 14 with multiplier 0.020000000000000004
Adjusting sigma at index 15 with multiplier 0.0
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 2847.30810546875 True
Requested to load Flux
Loading 1 new model
loaded completely 0.0 6490.570556640625 True
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:40<00:00,  2.54s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Prompt executed in 63.77 seconds
FETCH DATA from: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]FETCH DATA from: L:\ComfyUI_FLUX_1.0\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
```

**Comment by kk8bit** [comment]
Please provide me with a screenshot showing the connection setup of your nodes.

**Comment by kk8bit** [comment]
Hello,

Thank you for your feedback on the Custom Save Image node. I'm sorry to hear that it's not working as expected. Let's troubleshoot the issue:

File Permissions : Make sure that the user running ComfyUI has the necessary permissions to write to the output directory. Check if the directory L:\ComfyUI_FLUX_1.0\output\Custom_Save_Image exists and that you can write to it. If not, try creating it manually or ensure your account has write access.
Check for Errors : Look for any error messages in the console or logs (L:\ComfyUI_FLUX_1.0\comfyui.log) that might indicate why the images aren't being saved. There might be an exception or error occurring during the save process.
Path Issues : Ensure that the paths to ICC profiles (resources/sRGB Profile.icc and resources/AdobeRGB1998.icc) are correct relative to where ComfyUI is installed. If these files are missing or not in the expected location, the conversion to Adobe RGB might fail.
Node Configuration : Verify that your node is properly configured in the workflow. Check that the inputs for the images, filename_prefix, format, etc., are correctly connected and populated.
ComfyUI Version : You're using the latest commit, which is good. However, ensure there haven't been any recent changes or known issues with custom nodes in this version.
Python and Dependencies : Confirm that all necessary dependencies are installed correctly, especially Pillow for image processing. You can try reinstalling ComfyUI or updating its dependencies to ensure everything is up-to-date.
Testing with Different Inputs : Try saving images with different parameters, like changing the format to JPG or altering the filename prefix to see if it makes any difference.
If you still face issues after checking these points, please provide:

Any error messages or logs related to the Custom Save Image node.
A screenshot or description of your workflow configuration involving this node.
The content of the comfyui.log

**Comment by kk8bit** [comment]
Hello,

Thank you for your feedback on the Custom Save Image node. I'm sorry to hear that it's not working as expected. Let's troubleshoot the issue:

1. **File Permissions**: Make sure that the user running ComfyUI has the necessary permissions to write to the output directory. Check if the directory `L:\ComfyUI_FLUX_1.0\output\Custom_Save_Image` exists and that you can write to it. If not, try creating it manually or ensure your account has write access.

2. **Check for Errors**: Look for any error messages in the console or logs (`L:\ComfyUI_FLUX_1.0\comfyui.log`) that might indicate why the images aren't being saved. There might be an exception or error occurring during the save process.

3. **Path Issues**: Ensure that the paths to ICC profiles (`resources/sRGB Profile.icc` and `resources/AdobeRGB1998.icc`) are correct relative to where ComfyUI is installed. If these files are missing or not in the expected location, the conversion to Adobe RGB might fail.

4. **Node Configuration**: Verify that your node is properly configured in the workflow. Check that the inputs for the `images`, `filename_prefix`, `format`, etc., are correctly connected and populated.

5. **ComfyUI Version**: You're using the latest commit, which is good. However, ensure there haven't been any recent changes or known issues with custom nodes in this version.

6. **Python and Dependencies**: Confirm that all necessary dependencies are installed correctly, especially `Pillow` for image processing. You can try reinstalling ComfyUI or updating its dependencies to ensure everything is up-to-date.

7. **Testing with Different Inputs**: Try saving images with different parameters, like changing the format to JPG or altering the filename prefix to see if it makes any difference.

If you still face issues after checking these points, please provide:

- Any error messages or logs related to the Custom Save Image node.
- A screenshot or description of your workflow configuration involving this node.
- The content of the `comfyui.log` file after attempting to save an image.

This information will help in further diagnosing the problem. Thank you for your patience, and I look forward to helping you resolve this issue.

**Comment by DavideAlidosi** [comment]
I did some further checking, apparently the problem I have is related to the preview image not being displayed, I just now realized that the save works.
So the problem is that it saves without giving me the preview on Comfy.
I'm sorry for that.
![Preview issue](https://github.com/user-attachments/assets/c80bea3d-eed7-40c2-9700-86f6e9c456ab)
[Custom Save Image.json](https://github.com/user-attachments/files/17799558/Custom.Save.Image.json)

**Comment by DavideAlidosi** [comment]
I finally figured out what's going on, the saving of images happens in the main Comfy Protable folder. In patica it does this:
C:\comfyUI_portable\output\Custom_Save_Image
Instead of the way it should be:
C:\comfyUI_portable\ComfyUI\output\Custom_Save_Image

I also noticed that you cannot use dynamic tags to save, such as: %date:yyyy-MM-dd%
In this case the error is: [Errno 22] Invalid argument.

**Comment by kk8bit** [comment]
Thank you very much for your feedback. I will take the time to test and iterate on the version. In the meantime, you can use the Preview Image node as a temporary workaround for the preview issue. If the save function is working correctly (please verify if the image parameters are set as expected), you can use it.

**Comment by kk8bit** [comment]
Hey friend, after testing, image previews are working properly in the latest version of ComfyUI on both Windows and Linux. Let me know if you can give it another test to confirm everything runs smoothly on your end.

**Comment by kk8bit** [comment]
@DavideAlidosi Hi, friend! I've upgraded the Custom Save Image node. The latest version now supports a rich set of filename variables, a preview image function (temporary without saving), and improved compatibility for previews. The node package has also been expanded with a large number of practical nodes. Feel free to test it out!
